development:
  bucket_name: development-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1

test:
  bucket_name: test-bucket
  access_key_id: access_key
  secret_access_key: secret_key
  region: us-east-1
  
production:
  bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_BUCKET_REGION'] %>
