# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: canvas
  password: your_password
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  password: your_password
  timeout: 5000
  secondary:
    replica: true
    username: canvas_readonly_user

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000
